//This file was automatically generated by
//Matlab on 31-May-2009 12:11:08.
`include "sin.vh"

module sin(
    input [`SIN_INPUT_RANGE]       in,
    output reg [`SIN_OUTPUT_RANGE] out);

   always @(in) begin
     casez(in)
       `SIN_INPUT_WIDTH'd0: out <= `SIN_OUTPUT_WIDTH'd0;
       `SIN_INPUT_WIDTH'd1: out <= `SIN_OUTPUT_WIDTH'd1;
       `SIN_INPUT_WIDTH'd2: out <= `SIN_OUTPUT_WIDTH'd2;
       `SIN_INPUT_WIDTH'd3: out <= `SIN_OUTPUT_WIDTH'd3;
       `SIN_INPUT_WIDTH'd4: out <= `SIN_OUTPUT_WIDTH'd3;
       `SIN_INPUT_WIDTH'd5: out <= `SIN_OUTPUT_WIDTH'd3;
       `SIN_INPUT_WIDTH'd6: out <= `SIN_OUTPUT_WIDTH'd2;
       `SIN_INPUT_WIDTH'd7: out <= `SIN_OUTPUT_WIDTH'd1;
       `SIN_INPUT_WIDTH'd8: out <= `SIN_OUTPUT_WIDTH'd5;
       `SIN_INPUT_WIDTH'd9: out <= `SIN_OUTPUT_WIDTH'd6;
       `SIN_INPUT_WIDTH'd10: out <= `SIN_OUTPUT_WIDTH'd7;
       `SIN_INPUT_WIDTH'd11: out <= `SIN_OUTPUT_WIDTH'd7;
       `SIN_INPUT_WIDTH'd12: out <= `SIN_OUTPUT_WIDTH'd7;
       `SIN_INPUT_WIDTH'd13: out <= `SIN_OUTPUT_WIDTH'd6;
       `SIN_INPUT_WIDTH'd14: out <= `SIN_OUTPUT_WIDTH'd5;
       `SIN_INPUT_WIDTH'd15: out <= `SIN_OUTPUT_WIDTH'd0;
       default: out <= `SIN_OUTPUT_WIDTH'hx;
     endcase
   end
endmodule
