include ../components/common_header.mk

SOURCES+=$(COMPONENTS_DIR)/tracking_loops.csv \
	$(COMPONENTS_DIR)/sqrt_fixed.csv \
	$(COMPONENTS_DIR)/fll.csv \
	$(COMPONENTS_DIR)/dll.csv \
	$(COMPONENTS_DIR)/channel__dll.csv \
	$(COMPONENTS_DIR)/channel__tracking_loops.csv

include ../components/common.mk