include ../components/common_header.mk

SOURCES+=$(COMPONENTS_DIR)/acquisition_controller.csv \
	$(COMPONENTS_DIR)/channel__acquisition_controller.csv \
	$(COMPONENTS_DIR)/acquisition.csv

SOURCES+=$(COMPONENTS_DIR)/ca_upsampler.csv \
	$(COMPONENTS_DIR)/subchannel.csv \
	$(COMPONENTS_DIR)/cos.csv \
	$(COMPONENTS_DIR)/sin.csv \
	$(COMPONENTS_DIR)/channel__subchannel.csv \
	$(COMPONENTS_DIR)/channel__ca_upsampler.csv \
	$(COMPONENTS_DIR)/channel.csv \
	$(COMPONENTS_DIR)/mem_bank.csv

include ../components/common.mk