include ../components/common_header.mk

SOURCES+=$(COMPONENTS_DIR)/acquisition_controller.csv \
	$(COMPONENTS_DIR)/channel__acquisition_controller.csv \
	$(COMPONENTS_DIR)/acquisition.csv

include ../components/common.mk