%script file CONSTANT_H.m
%declares all variables as globals, rather than re-declaring all variables
%upon each function call
global AMP A_FLL A_PLL B_FLL CARRIER_THRESHOLD CA_FREQ CHIP CHIPS_EML CNO_MIN DEBUGFLAG FC FD_SIZE FREQ_BINS FREQ_STEP
global FSAMP_MSEC HNUM INITIALIZE_PLL K_PLL L1 NBS ONE_MSEC_SAM PLL_LOOP_ORDER SNR_FLOOR T TP T_QUARTER_CHIP T_RES USE_PLL W_FC
global PLL_SWITCH_TIME NUM_CHIPS USE_FFT CNO_MIN_COUNTS B_PLL