function table=lookup_table(type,quantization,width,module,outputDir)
    num_entries=2^width;
    max_value=2^(quantization-1)-1;
    
    if(strcmpi(type,'sin'))
        table=round(max_value*(sin(linspace(0,2*pi,num_entries))'));
    elseif(strcmpi(type,'cos'))
        table=round(max_value*(cos(linspace(0,2*pi,num_entries))'));
    else
        table=zeros(num_entries,1);
    end
    
    negative=table<0;
    table=abs(table);
    table=bitxor(table,2^(quantization-1)*negative);
    
    if(~isempty(module))
        if(isempty(outputDir))
            outputDir='.';
        elseif(outputDir(end)=='/')
            outputDir=outputDir(1:end-1);
        end
        
        const=upper(module);
        
        %Print header definition file.
        f=fopen(sprintf('%s/%s.csv',outputDir,module),'wt');
        
        fprintf(f,'//This file was automatically generated by\n');
        fprintf(f,'//Matlab on %s.\n',datestr(now));
        fprintf(f,'\n');
        fprintf(f,'%s_INPUT_WIDTH,%d,%s lookup table input width.\n',const,width,module);
        fprintf(f,'%s_INPUT_RANGE,%s_INPUT_WIDTH-1:0,%s lookup table input bit range.\n',const,const,module);
        fprintf(f,'\n');
        fprintf(f,'%s_OUTPUT_WIDTH,%d,%s lookup table output width.\n',const,quantization,module);
        fprintf(f,'%s_OUTPUT_RANGE,%s_OUTPUT_WIDTH-1:0,%s lookup table output bit range.\n',const,const,module);
        
        fclose(f);
        
        %Print module.
        f=fopen(sprintf('%s/%s.v',outputDir,module),'wt');
        
        fprintf(f,'//This file was automatically generated by\n');
        fprintf(f,'//Matlab on %s.\n',datestr(now));
        fprintf(f,'`include "%s"\n',sprintf('%s.vh',module));
        fprintf(f,'\n');
        
        fprintf(f,'module %s(\n',module);
        fprintf(f,'    input [`%s_INPUT_RANGE]       in,\n',const);
        fprintf(f,'    output reg [`%s_OUTPUT_RANGE] out);\n',const);
        fprintf(f,'\n');
        fprintf(f,'   always @(in) begin\n');
        fprintf(f,'     casez(in)\n');
        for i=1:num_entries
          fprintf(f,'       `%s_INPUT_WIDTH\''d%d: out <= `%s_OUTPUT_WIDTH\''d%d;\n',...
                const,i-1,...
                const,table(i));
        end
        fprintf(f,'       default: out <= `%s_OUTPUT_WIDTH\''hx;\n',const);
        fprintf(f,'     endcase\n');
        fprintf(f,'   end\n');
        fprintf(f,'endmodule\n');
        
        fclose(f);
    end
end