include ../components/common.mk

SOURCES+=$(COMPONENTS_DIR)/ca_upsampler.csv \
	$(COMPONENTS_DIR)/subchannel.csv \
	$(COMPONENTS_DIR)/cos.csv \
	$(COMPONENTS_DIR)/sin.csv \
	$(COMPONENTS_DIR)/channel__subchannel.csv \
	$(COMPONENTS_DIR)/channel.csv \
	top__channel.csv