include ../components/common_header.mk

SOURCES+=$(COMPONENTS_DIR)/ca_upsampler.csv \
	$(COMPONENTS_DIR)/subchannel.csv \
	$(COMPONENTS_DIR)/cos.csv \
	$(COMPONENTS_DIR)/sin.csv \
	$(COMPONENTS_DIR)/channel__subchannel.csv \
	$(COMPONENTS_DIR)/channel__ca_upsampler.csv \
	$(COMPONENTS_DIR)/channel.csv \
	$(COMPONENTS_DIR)/acquisition_controller.csv \
	$(COMPONENTS_DIR)/channel__acquisition_controller.csv \
	$(COMPONENTS_DIR)/tracking_loops.csv \
	$(COMPONENTS_DIR)/sqrt_fixed.csv \
	$(COMPONENTS_DIR)/fll.csv \
	$(COMPONENTS_DIR)/dll.csv \
	$(COMPONENTS_DIR)/channel__dll.csv \
	$(COMPONENTS_DIR)/channel__tracking_loops.csv \
	$(COMPONENTS_DIR)/mem_bank.csv \
	../rt_data_feed/dm9000a_controller.csv \
	../rt_data_feed/rtdf_packet_processor.csv \
#	top__channel.csv

include ../components/common.mk